# SPDX-FileCopyrightText: © 2021 Matt Williams <matt@milliams.com>
# SPDX-License-Identifier: MIT

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
