name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: jetli/wasm-pack-action@v0.3.0
    - name: Build
      run: wasm-pack build --no-typescript --target web
    - name: Run tests
      run: wasm-pack test --chrome --headless
    - name: Install resuse
      run: pip install reuse
    - name: Check REUSE spec
      run: reuse lint
    - name: assemble assets
      run: |
        mkdir -p public
        cp -r static/* public/
        cp -r pkg public/
    - name: Publish
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=public --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
