name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: jetli/wasm-pack-action@v0.3.0
    - name: Build
      run: wasm-pack build --no-typescript --target web
    - name: Run tests
      run: wasm-pack test --chrome --headless
    - name: assemble assets
      run: |
        mkdir -p public
        cp -r static/* public/
        cp -r pkg/* public/
    - uses: actions/upload-artifact@v2
      with:
        name: site
        path: public
